# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockapi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estockapi.proto\x12\x08stockapi\"(\n\nAPIRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"b\n\tAPIReturn\x12\x0c\n\x04\x64\x61te\x18\x01 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\x12\x12\n\nprediction\x18\x03 \x01(\x02\x12\x15\n\rrecomandation\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t2J\n\x0fStockPrediction\x12\x37\n\x08getStock\x12\x14.stockapi.APIRequest\x1a\x13.stockapi.APIReturn\"\x00\x42\x0cZ\n./stockapib\x06proto3')



_APIREQUEST = DESCRIPTOR.message_types_by_name['APIRequest']
_APIRETURN = DESCRIPTOR.message_types_by_name['APIReturn']
APIRequest = _reflection.GeneratedProtocolMessageType('APIRequest', (_message.Message,), {
  'DESCRIPTOR' : _APIREQUEST,
  '__module__' : 'stockapi_pb2'
  # @@protoc_insertion_point(class_scope:stockapi.APIRequest)
  })
_sym_db.RegisterMessage(APIRequest)

APIReturn = _reflection.GeneratedProtocolMessageType('APIReturn', (_message.Message,), {
  'DESCRIPTOR' : _APIRETURN,
  '__module__' : 'stockapi_pb2'
  # @@protoc_insertion_point(class_scope:stockapi.APIReturn)
  })
_sym_db.RegisterMessage(APIReturn)

_STOCKPREDICTION = DESCRIPTOR.services_by_name['StockPrediction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./stockapi'
  _APIREQUEST._serialized_start=28
  _APIREQUEST._serialized_end=68
  _APIRETURN._serialized_start=70
  _APIRETURN._serialized_end=168
  _STOCKPREDICTION._serialized_start=170
  _STOCKPREDICTION._serialized_end=244
# @@protoc_insertion_point(module_scope)
